import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,symlink,link} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {readStandingEpochRecovery as read,writeStandingEpochRecovery as write} from './rm-0032-standing-epoch-recovery.mjs';
const epochId='a'.repeat(32),digest=x=>createHash('sha256').update(x).digest('hex');
async function fixture(t){const root=await mkdtemp(join(tmpdir(),'epoch-recovery-'));t.after(()=>rm(root,{recursive:true,force:true}));const directory=join(root,epochId);await mkdir(directory);
 const intent=JSON.stringify({operation:'standing-native-epoch-v1',token:epochId,workerToken:'b'.repeat(32)})+'\n',controller=JSON.stringify({version:'standing-controller-v1',token:epochId,workerToken:'b'.repeat(32),pid:123})+'\n';
 await writeFile(join(directory,'intent.json'),intent);await writeFile(join(directory,'controller.json'),controller);
 const input={directory,epochId,authorizationHash:'c'.repeat(64),intentHash:digest(intent),controllerHash:digest(controller),checkPhysicalSettlement:async()=>({exclusiveCustody:true,windowsBeforeAbsent:true,guestAbsent:true,windowsAfterAbsent:true,checkedAt:new Date().toISOString(),receiptHash:'d'.repeat(64)})};return {input,intent,controller};}
test('separate one-shot physical proof preserves original files and unknown model outcome',async t=>{const {input,intent,controller}=await fixture(t);assert.equal(await read(input),undefined);const result=await write(input);assert.equal(result.modelOutcome,'not-proven');assert.equal(result.resourcesSettled,true);assert.equal(result.receipt.authorizationHash,input.authorizationHash);await assert.rejects(write(input));assert.equal(await readFile(join(input.directory,'intent.json'),'utf8'),intent);assert.equal(await readFile(join(input.directory,'controller.json'),'utf8'),controller);await assert.rejects(readFile(join(input.directory,'actual.json')),{code:'ENOENT'});});
test('actual existing is never overridden',async t=>{const {input}=await fixture(t);await writeFile(join(input.directory,'actual.json'),'{}\n');await assert.rejects(write(input));});
test('stale or negative physical proof refuses receipt',async t=>{const {input}=await fixture(t);const p=await input.checkPhysicalSettlement();for(const physical of [{...p,guestAbsent:false},{...p,checkedAt:new Date(Date.now()-61000).toISOString()}])await assert.rejects(write({...input,checkPhysicalSettlement:async()=>physical}));});
test('callback getter, toJSON and proxy are rejected without executing hooks',async t=>{const {input}=await fixture(t),p=await input.checkPhysicalSettlement();let invoked=0;
 const getter={...p};Object.defineProperty(getter,'guestAbsent',{enumerable:true,get(){invoked++;return true;}});
 const serializer={...p,toJSON(){invoked++;return p;}};
 const proxy=new Proxy(p,{ownKeys(){invoked++;return Reflect.ownKeys(p);},getPrototypeOf(){invoked++;return Object.prototype;}});
 for(const value of [getter,serializer,proxy])await assert.rejects(write({...input,checkPhysicalSettlement:async()=>value}));
 assert.equal(invoked,0);await assert.rejects(readFile(join(input.directory,'recovery.json')),{code:'ENOENT'});
});
test('exact hash and foreign binding mismatch fail closed',async t=>{const {input}=await fixture(t);await assert.rejects(write({...input,intentHash:'0'.repeat(64)}));await assert.rejects(write({...input,epochId:'e'.repeat(32)}));});
test('source mutation during check refuses append',async t=>{const {input}=await fixture(t);await assert.rejects(write({...input,checkPhysicalSettlement:async()=>{await writeFile(join(input.directory,'controller.json'),'{}\n');return input.checkPhysicalSettlement();}}));});
test('torn receipt fails closed',async t=>{const {input}=await fixture(t);await writeFile(join(input.directory,'recovery.json'),'{');await assert.rejects(read(input));});
test('receipt hash mismatch and missing controller fail closed',async t=>{const {input}=await fixture(t);await write(input);const path=join(input.directory,'recovery.json'),r=JSON.parse(await readFile(path,'utf8'));r.controllerHash='0'.repeat(64);await writeFile(path,JSON.stringify(r)+'\n');await assert.rejects(read(input));await rm(join(input.directory,'controller.json'));await assert.rejects(read(input));});
test('valid receipt then changed source or appeared actual fails closed',async t=>{const {input}=await fixture(t);await write(input);await writeFile(join(input.directory,'actual.json'),'{}\n');await assert.rejects(read(input));await rm(join(input.directory,'actual.json'));await writeFile(join(input.directory,'intent.json'),'{}\n');await assert.rejects(read(input));});
test('symlink receipt fails closed',async t=>{const {input}=await fixture(t);const target=join(input.directory,'target.json');await writeFile(target,'{}\n');try{await symlink(target,join(input.directory,'recovery.json'));}catch(e){if(e.code==='EPERM'){t.skip('symlink privilege unavailable');return;}throw e;}await assert.rejects(read(input));});
test('foreign publication alias is invalid evidence, never a missing final receipt',async t=>{const {input}=await fixture(t);await write(input);
 await link(join(input.directory,'recovery.json'),join(input.directory,'foreign-alias.json'));
 await assert.rejects(read(input),{code:'RECOVERY'});
});
