/** Account-independent schema inspection, generated by the installed CLI 2026-10-04. */
export const supportedAppServerProtocol = {
  cliVersion: '0.160.0', transport: 'stdio://', experimentalApi: false,
  methods: ['initialize', 'initialized', 'thread/list', 'thread/read', 'thread/start', 'turn/start', 'turn/steer', 'turn/interrupt'],
  documentation: 'https://learn.chatgpt.com/docs/app-server',
  notes: [
    'turn/steer requires expectedTurnId and cannot override the sandbox.',
    'thread/list uses sourceKinds appServer and useStateDbOnly; unknown desktop ownership is not imported.',
    'Installed stable schema has readOnly networkAccess and workspaceWrite writableRoots; restricted read access in newer docs is not present here.',
    'Sandbox flags and CODEX_HOME do not attest OS/secret isolation; an executor boundary receipt is required.',
  ],
} as const;
